// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWj_Dv2QHEw_voCpsOi8Z_UFnSsApNi7g',
    appId: '1:318022767331:web:aca8b266d62ac799e82bd6',
    messagingSenderId: '318022767331',
    projectId: 'ecommerce-e0ae3',
    authDomain: 'ecommerce-e0ae3.firebaseapp.com',
    storageBucket: 'ecommerce-e0ae3.appspot.com',
    measurementId: 'G-2SD4WPJC8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwVwgI-bZgmbD5hzg3XR-4HHXUZWzaabw',
    appId: '1:318022767331:android:2c9531facad05701e82bd6',
    messagingSenderId: '318022767331',
    projectId: 'ecommerce-e0ae3',
    storageBucket: 'ecommerce-e0ae3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzCcFUgI9uL-Edfwd4GpVHgmm9ybZ3mKs',
    appId: '1:318022767331:ios:c08ca380ddf62592e82bd6',
    messagingSenderId: '318022767331',
    projectId: 'ecommerce-e0ae3',
    storageBucket: 'ecommerce-e0ae3.appspot.com',
    iosClientId: '318022767331-onak9pu6qr5d91ds0icelu13ohc711op.apps.googleusercontent.com',
    iosBundleId: 'com.example.iti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzCcFUgI9uL-Edfwd4GpVHgmm9ybZ3mKs',
    appId: '1:318022767331:ios:504183c9370e6a8ee82bd6',
    messagingSenderId: '318022767331',
    projectId: 'ecommerce-e0ae3',
    storageBucket: 'ecommerce-e0ae3.appspot.com',
    iosClientId: '318022767331-1r0onpkhk28vjav4hgvulb0dm6791a41.apps.googleusercontent.com',
    iosBundleId: 'com.example.iti.RunnerTests',
  );
}
